import { artifacts, ethers } from "hardhat";
import { writeFileSync } from "fs";
import { resolve } from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);

  const AttestationRegistry = await ethers.getContractFactory("AttestationRegistry");
  const attestationRegistry = await AttestationRegistry.deploy();
  await attestationRegistry.waitForDeployment();

  const ContributorRegistry = await ethers.getContractFactory("ContributorRegistry");
  const contributorRegistry = await ContributorRegistry.deploy();
  await contributorRegistry.waitForDeployment();

  const RewardDistributor = await ethers.getContractFactory("RewardDistributor");
  const rewardDistributor = await RewardDistributor.deploy(await attestationRegistry.getAddress());
  await rewardDistributor.waitForDeployment();

  const addresses = {
    attestationRegistry: await attestationRegistry.getAddress(),
    contributorRegistry: await contributorRegistry.getAddress(),
    rewardDistributor: await rewardDistributor.getAddress(),
  };

  console.log("AttestationRegistry:", addresses.attestationRegistry);
  console.log("ContributorRegistry:", addresses.contributorRegistry);
  console.log("RewardDistributor:", addresses.rewardDistributor);

  const outPath = resolve(__dirname, "../deployed.json");
  writeFileSync(outPath, JSON.stringify(addresses, null, 2));

  const attestationRegistryArtifact = await artifacts.readArtifact("AttestationRegistry");
  const contributorRegistryArtifact = await artifacts.readArtifact("ContributorRegistry");
  const rewardDistributorArtifact = await artifacts.readArtifact("RewardDistributor");

  const generated = `// AUTO-GENERATED by scripts/deploy.ts — do not edit by hand.
export const contractAddresses = ${JSON.stringify(addresses, null, 2)} as const;

export const attestationRegistryAbi = ${JSON.stringify(attestationRegistryArtifact.abi, null, 2)} as const;

export const contributorRegistryAbi = ${JSON.stringify(contributorRegistryArtifact.abi, null, 2)} as const;

export const rewardDistributorAbi = ${JSON.stringify(rewardDistributorArtifact.abi, null, 2)} as const;

export const contracts = {
  attestationRegistry: { address: contractAddresses.attestationRegistry, abi: attestationRegistryAbi },
  contributorRegistry: { address: contractAddresses.contributorRegistry, abi: contributorRegistryAbi },
  rewardDistributor: { address: contractAddresses.rewardDistributor, abi: rewardDistributorAbi },
} as const;
`;

  const generatedOutPath = resolve(__dirname, "../generated.ts");
  writeFileSync(generatedOutPath, generated);

  const sharedGeneratedPath = resolve(__dirname, "../../shared/src/contracts.generated.ts");
  writeFileSync(sharedGeneratedPath, generated);

  console.log("Wrote", outPath);
  console.log("Wrote", generatedOutPath);
  console.log("Wrote", sharedGeneratedPath);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
