// AUTO-GENERATED by scripts/deploy.ts — do not edit by hand.
export const contractAddresses = {
  "attestationRegistry": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  "contributorRegistry": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  "rewardDistributor": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
} as const;

export const attestationRegistryAbi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "reason",
        "type": "string"
      }
    ],
    "name": "BatchDisputed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      }
    ],
    "name": "BatchExpired",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      }
    ],
    "name": "BatchSubmitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "witnesses",
        "type": "address[]"
      }
    ],
    "name": "BatchValidated",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "EXPIRY_SECONDS",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "witness",
        "type": "address"
      }
    ],
    "name": "attest",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "batches",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "storageCID",
        "type": "string"
      },
      {
        "internalType": "bytes8",
        "name": "geohashPrefix",
        "type": "bytes8"
      },
      {
        "internalType": "uint32",
        "name": "pointCount",
        "type": "uint32"
      },
      {
        "internalType": "uint64",
        "name": "submittedAt",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "validatedAt",
        "type": "uint64"
      },
      {
        "internalType": "enum AttestationRegistry.Status",
        "name": "status",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "reason",
        "type": "string"
      }
    ],
    "name": "dispute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      }
    ],
    "name": "expire",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      }
    ],
    "name": "getBatch",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "dataHash",
            "type": "bytes32"
          },
          {
            "internalType": "string",
            "name": "storageCID",
            "type": "string"
          },
          {
            "internalType": "bytes8",
            "name": "geohashPrefix",
            "type": "bytes8"
          },
          {
            "internalType": "uint32",
            "name": "pointCount",
            "type": "uint32"
          },
          {
            "internalType": "address[]",
            "name": "witnesses",
            "type": "address[]"
          },
          {
            "internalType": "uint64",
            "name": "submittedAt",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "validatedAt",
            "type": "uint64"
          },
          {
            "internalType": "enum AttestationRegistry.Status",
            "name": "status",
            "type": "uint8"
          }
        ],
        "internalType": "struct AttestationRegistry.Batch",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "storageCID",
        "type": "string"
      },
      {
        "internalType": "bytes8",
        "name": "geohashPrefix",
        "type": "bytes8"
      },
      {
        "internalType": "uint32",
        "name": "pointCount",
        "type": "uint32"
      }
    ],
    "name": "submitBatch",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

export const contributorRegistryAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "contributors",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "reputation",
        "type": "uint16"
      },
      {
        "internalType": "uint32",
        "name": "validatedPoints",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "rejectedPoints",
        "type": "uint32"
      },
      {
        "internalType": "uint256",
        "name": "stakedAmount",
        "type": "uint256"
      },
      {
        "internalType": "enum ContributorRegistry.Tier",
        "name": "tier",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      },
      {
        "internalType": "uint32",
        "name": "points",
        "type": "uint32"
      }
    ],
    "name": "recordValidation",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      }
    ],
    "name": "register",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

export const rewardDistributorAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_attestationRegistry",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "RewardClaimed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "RewardRecorded",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "attestationRegistry",
    "outputs": [
      {
        "internalType": "contract IAttestationRegistry",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "claim",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      }
    ],
    "name": "claimFor",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "claimed",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      }
    ],
    "name": "claimedOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "pending",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      }
    ],
    "name": "pendingOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "batchId",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "contributor",
        "type": "address"
      }
    ],
    "name": "recordReward",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

export const contracts = {
  attestationRegistry: { address: contractAddresses.attestationRegistry, abi: attestationRegistryAbi },
  contributorRegistry: { address: contractAddresses.contributorRegistry, abi: contributorRegistryAbi },
  rewardDistributor: { address: contractAddresses.rewardDistributor, abi: rewardDistributorAbi },
} as const;
